import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from 'next/router';
import {useState} from 'react';

export default function Index(){
  const router = useRouter();    
  const [input, setInput] = useState<string>();

  const clickButton = () => {
    //未入力の時
    if (!input) {
      return;
    }

    localStorage.setItem('asdf', input);
    router.push({
        pathname:"/record",   //URL
        query: {input :input} //検索クエリ
      });
  }

  return (
    <div className={styles.container}>
      <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className="bg-white">
      <div className="border-2 border-black text-center">
        <h1 className={"text-3xl"}>
          ログイン
        </h1>
        <form className="px-6 mt-4 mb-4 w-full,text-align">
         <input type="text" value={input} onChange={(e) => setInput(e.target.value)} placeholder="メールアドレス/id" className = "border-2 border-black"></input>
        </form>
        <form className="px-6 mt-4 mb-4 w-full,text-align">
         <input type="password" placeholder="パスワード" className = "border-2 border-black"></input>
        </form>
          <div className={"w-32 text-align text-white border-2 border-black rounded-full py-2 px-3 text-2xl bg-red-400"}>
          <button onClick={clickButton}>ログイン</button></div>
        </div>
        </div>
      </main>
    </div>
    </div>
  );
};
