import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { unstable_renderSubtreeIntoContainer } from "react-dom";
import styles from "../styles/Home.module.css";
import { activateLasers } from "./api/hello";
import Link from 'next/link';

const Home: NextPage = () => {


  return (
    <div className={styles.container}>
      <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <main className={styles.main}>
        <div className="bg-white">
      <div className="border-2 border-black text-center">
        <h1 className={"text-3xl"}>
          ログイン
        </h1>

        <form className="px-6 mt-4 mb-4 w-full,text-align">
          <div>メールアドレス/id</div>
         <input className = "border-2 border-black"></input>
        </form>

        <form className="px-6 mt-4 mb-4 w-full,text-align">
        <div>パスワード</div>
         <input className = "border-2 border-black"></input>
        </form>

        <ul>
         <li>
           
          <button className={"text-white border-2 rounded-full py-2 px-3 text-2xl bg-red-400"}>
           <Link href="/record">
            <a>ログイン</a>
           </Link>
          </button>
        </li>
       </ul>
        </div>
        </div>
      </main>
    </div>
    </div>
  );
};

export default Home;
