import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from 'next/link';
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  console.log(router.query.name)

    return (
      <div className={styles.container}>
        <div className="bg-gray-100">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <header className="text-right border-2 border-black">
        <>
        <div>{ 'こんちわ' + router.query.input}</div>
        </>
          </header>
        
           <main className={styles.table}>
           <div className="grid grid-cols-5 gap-2">

           <div className="col-span-1 border-2 border-black">              
               <Link href="/record">
               <a>Home</a>
               </Link>
               <Link href="/user">
                <a>ユーザー管理</a>
               </Link>
             </div>

            <div className="col-span-4">
             <h3>履歴</h3>
              <div className="pl-20 bg-gray-100">
               <table>
                
                 <tbody className="border-2 border-black py-4">
                  <tr className="border-2 border-black">
                   <th>日付</th>
                   <th>ユーザー</th>
                   <th>内容</th>
                  </tr>
                  <tr>
                   <td>2020/6/18</td>
                   <td>user1</td>
                   <td>ユーザーを作成しました</td>
                  </tr>
                  <tr>
                   <td>2020/6/20</td>
                   <td>user1</td>
                   <td>ユーザーを作成しました</td>
                  </tr>
                  <tr>
                   <td>2020/6/30</td>
                   <td>user2</td>
                   <td>ユーザーを作成しました</td>
                  </tr>
                 </tbody>
                
               </table>
              </div>
             </div>
            </div>
            </main>
           </div>
          </div>
    );
  };
  
  export default Home;
  