import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { unstable_renderSubtreeIntoContainer } from "react-dom";
import styles from "../styles/Home.module.css";
import { activateLasers } from "./api/hello";
import Link from 'next/link';

const Home: NextPage = () => {

    return (
      <div className={styles.container}>
        <div className="bg-gray-100">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <header className="text-right border-2 border-black">
          UserNmame
          </header>
        
           <main className={styles.table}>
           <div className="grid grid-cols-5 gap-2">

           <div className="col-span-1">
              <aside className="border-2 border-black">
               <Link href="/record">
               <a>Home</a>
               </Link>
               <Link href="/user">
                <a>ユーザー管理</a>
               </Link>
              </aside>
             </div>

            <div className="col-span-4">
             <h3>履歴</h3>
              <div className="pl-20 bg-gray-100">
               <table>
                <div className="py-4">
                 <tbody className="border-2 border-black">
                  <tr className="border-2 border-black">
                   <th>日付</th>
                   <th>ユーザー</th>
                   <th>内容</th>
                  </tr>
                  <tr>
                   <td>2020/6/18</td>
                   <td>user1</td>
                   <td>ユーザーを作成しました</td>
                  </tr>
                  <tr>
                   <td>2020/6/20</td>
                   <td>user1</td>
                   <td>ユーザーを作成しました</td>
                  </tr>
                  <tr>
                   <td>2020/6/30</td>
                   <td>user2</td>
                   <td>ユーザーを作成しました</td>
                  </tr>
                 </tbody>
                </div>
               </table>
              </div>
             </div>
            </div>
            </main>
           </div>
          </div>
    );
  };
  
  export default Home;
  