import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { unstable_renderSubtreeIntoContainer } from "react-dom";
import styles from "../styles/Home.module.css";
import { activateLasers } from "./api/hello";
import Link from 'next/link';

const Home: NextPage = () => {

    return (
      <div className={styles.container}>
        <div className="bg-gray-100">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <header className="text-right border-2 border-black">
          UserNmame
          </header>

          
           <main className={styles.table}>
           <div className="grid grid-cols-5 gap-2">

           <div className="col-span-1">
              <aside className="border-2 border-black">
               <Link href="/record">
               <a>Home</a>
               </Link>
               <Link href="/record">
                <a>ユーザー管理</a>
               </Link>
              </aside>
             </div>

            <div className="col-span-4">
                <h3>権限</h3>
                <form className="px-6 mt-4 mb-4 w-full,text-align">
          <div>メールアドレス/id</div>
         <input className = "border-2 border-black"></input>
        </form>
        

             <h3>ユーザー一覧</h3>
              <div className="pl-20 bg-gray-100">
               <table>
                <div className="py-4">
                 <tbody className="border-2 border-black">
                  <tr className="border-2 border-black">
                   <th>id</th>
                   <th>名前</th>
                   <th>メールアドレス</th>
                   <th>権限</th>
                  </tr>
                  <tr>
                   <td>id_1</td>
                   <td>user1</td>
                   <td>user1@gmail.com</td>
                   <td>管理者</td>
                  </tr>
                  <tr>
                   <td>id_2</td>
                   <td>user2</td>
                   <td>user2@gmail.com</td>
                   <td>管理者</td>
                  </tr>
                  <tr>
                   <td>id_3</td>
                   <td>user3</td>
                   <td>user3@gmail.com</td>
                   <td>ユーザー</td>
                  </tr>
                  <tr>
                    <td>id_4</td>
                    <td>user4</td>
                    <td>user4@gmail.com</td>
                    <td>管理者</td>
                   </tr>
                   <tr>
                       <td>id_5</td>
                       <td>user5</td>
                       <td>user5@gmail.com</td>
                       <td>ユーザー</td>
                   </tr>
                  
                 </tbody>
                </div>
               </table>
              </div>
             </div>
            </div>
            </main>
           </div>
          </div>
    );
  };
  
  export default Home;
  